name: Run C Program

on: [push, pull_request]

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install GCC
        run: sudo apt update && sudo apt install -y build-essential

      - name: Compile C program
        run: gcc main.c -o insurance

      - name: Run C program
        run: |
          echo "Program output:"
          ./insurance < .github/workflows/input.txt || echo "Please provide input if needed"
